#ifndef HAL_CONFIG_H
#define HAL_CONFIG_H

#include "em_device.h"
#include "hal-config-types.h"

// This file is auto-generated by Hardware Configurator in Simplicity Studio.
// Any content between $[ and ]$ will be replaced whenever the file is regenerated.
// Content outside these regions will be preserved.

// $[ACMP0]
// [ACMP0]$

// $[ACMP1]
// [ACMP1]$

// $[ADC0]
// [ADC0]$

// $[BTL_BUTTON]
// [BTL_BUTTON]$

// $[BUTTON]
// [BUTTON]$

// $[CMU]
// [CMU]$

// $[DAC0]
// [DAC0]$

// $[EBI]
// [EBI]$

// $[EMU]
// [EMU]$

// $[EXTFLASH]
// [EXTFLASH]$

// $[GPIO]
#define PORTIO_GPIO_SWCLK_PIN         (0U)
#define PORTIO_GPIO_SWCLK_PORT        (gpioPortF)
#define PORTIO_GPIO_DBGROUTE_LOC      (0U)

#define PORTIO_GPIO_SWDIO_PIN         (1U)
#define PORTIO_GPIO_SWDIO_PORT        (gpioPortF)

// [GPIO]$

// $[I2C0]
// [I2C0]$

// $[I2C1]
// [I2C1]$

// $[I2CSENSOR]
// [I2CSENSOR]$

// $[IOEXP]
// [IOEXP]$

// $[LCD]
// [LCD]$

// $[LED]
// [LED]$

// $[LESENSE]
// [LESENSE]$

// $[LETIMER0]
// [LETIMER0]$

// $[LEUART0]
// [LEUART0]$

// $[LEUART1]
// [LEUART1]$

// $[LFXO]
// [LFXO]$

// $[MSC]
// [MSC]$

// $[PCNT0]
// [PCNT0]$

// $[PCNT1]
// [PCNT1]$

// $[PCNT2]
// [PCNT2]$

// $[PORTIO]
// [PORTIO]$

// $[PRS]
// [PRS]$

// $[SERIAL]
// [SERIAL]$

// $[SPIDISPLAY]
// [SPIDISPLAY]$

// $[SPINCP]
// [SPINCP]$

// $[TIMER0]
// [TIMER0]$

// $[TIMER1]
// [TIMER1]$

// $[TIMER2]
// [TIMER2]$

// $[TIMER3]
// [TIMER3]$

// $[UART0]
// [UART0]$

// $[UART1]
// [UART1]$

// $[UARTNCP]
// [UARTNCP]$

// $[USART0]
#define PORTIO_USART0_CLK_PIN         (12U)
#define PORTIO_USART0_CLK_PORT        (gpioPortE)
#define PORTIO_USART0_ROUTE_LOC       (0U)

#define PORTIO_USART0_CS_PIN          (13U)
#define PORTIO_USART0_CS_PORT         (gpioPortE)

#define PORTIO_USART0_TX_PIN          (10U)
#define PORTIO_USART0_TX_PORT         (gpioPortE)

#define HAL_USART0_ENABLE             (1)

#define BSP_USART0_MOSI_PIN           (10U)
#define BSP_USART0_MOSI_PORT          (gpioPortE)
#define BSP_USART0_ROUTE_LOC          (0U)

#define BSP_USART0_CLK_PIN            (12U)
#define BSP_USART0_CLK_PORT           (gpioPortE)

#define BSP_USART0_CS_PIN             (13U)
#define BSP_USART0_CS_PORT            (gpioPortE)

#define HAL_USART0_FREQUENCY          (1000000UL)
// [USART0]$

// $[USART1]
#define PORTIO_USART1_CLK_PIN         (2U)
#define PORTIO_USART1_CLK_PORT        (gpioPortD)
#define PORTIO_USART1_ROUTE_LOC       (1U)

#define PORTIO_USART1_CS_PIN          (3U)
#define PORTIO_USART1_CS_PORT         (gpioPortD)

#define PORTIO_USART1_RX_PIN          (1U)
#define PORTIO_USART1_RX_PORT         (gpioPortD)

#define PORTIO_USART1_TX_PIN          (0U)
#define PORTIO_USART1_TX_PORT         (gpioPortD)

#define HAL_USART1_ENABLE             (1)

#define BSP_USART1_MOSI_PIN           (0U)
#define BSP_USART1_MOSI_PORT          (gpioPortD)
#define BSP_USART1_ROUTE_LOC          (1U)

#define BSP_USART1_MISO_PIN           (1U)
#define BSP_USART1_MISO_PORT          (gpioPortD)

#define BSP_USART1_CLK_PIN            (2U)
#define BSP_USART1_CLK_PORT           (gpioPortD)

#define BSP_USART1_CS_PIN             (3U)
#define BSP_USART1_CS_PORT            (gpioPortD)

#define HAL_USART1_FREQUENCY          (1000000UL)
// [USART1]$

// $[USART2]
// [USART2]$

// $[USB]
// [USB]$

// $[VCOM]
// [VCOM]$

// $[WDOG]
// [WDOG]$

#if defined(_SILICON_LABS_MODULE)
#include "sl_module.h"
#endif

#endif /* HAL_CONFIG_H */

